# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f025c39bc0e239222faf9ce82133637e4eaa294bff10ec3f9d7507bb2c5ad1bed16b8e765554d1dd86c64ded5344b558efcd2df0b758283afd998387113c1951

test:
  secret_key_base: 8d0739fc02099d1fa30c6489d8a6871605f1cd9c6939d53263775e8bbc3c7c5f2d5c30442bb2a511ef7579f7bb8db695e01d36ef9be43dd156671c52e2cd1eda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
